# Generated by Django 5.0.4 on 2024-05-05 16:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inhabitant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Premise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Premise_Inhabitant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkIn_date', models.DateTimeField(default=datetime.datetime(2024, 5, 5, 16, 26, 39, 898081, tzinfo=datetime.timezone.utc))),
                ('checkOut_date', models.DateTimeField(default=datetime.datetime(2024, 5, 6, 16, 26, 39, 898081, tzinfo=datetime.timezone.utc))),
                ('inhabitant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.inhabitant')),
                ('premise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.premise')),
            ],
        ),
    ]
